# Generated by Django 2.1.7 on 2019-04-01 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20190401_1527'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
