# Generated by Django 2.1.7 on 2019-04-01 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='there is invalid char in used', regex='^[A-Za-z0-9]+$')])),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='there is invalid char in used', regex='^[A-Za-z0-9]+$')])),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
