# Generated by Django 2.1.7 on 2019-04-01 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_auto_20190401_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='nick_name',
            new_name='nickname',
        ),
    ]
