# Generated by Django 2.1.7 on 2019-04-01 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_auto_20190401_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='user_id',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='there is invalid char in used', regex='^[A-Za-z0-9]+$')]),
        ),
    ]
